### ISSUE TITLE
[Bug report] md文件存放目录名称为中文名称时，文档侧边栏不显示

### ISSUE THREAD

**Issue by wds-job** [vuepress/ecosystem#103]
### Description

md文档存放在中文路径下 ，并正确配置sidebar，navbar，文档标题不在侧边栏中展示

**Comment by Mister-Hope** [comment]
A valid reproduction is required.

**Comment by Mister-Hope** [comment]
We would happy to reopen it once you provide a minimal reproducion

**Comment by wds-job** [comment]
This is a Test Demo 
[docs.zip](https://github.com/vuepress/ecosystem/files/14953005/docs.zip)

**Comment by Mister-Hope** [comment]
> 文档标题不在侧边栏中展示

你的有效侧边栏配置在哪？

**Comment by Mister-Hope** [comment]
This might need to be fixed upstream at vuepress/core

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/core/commit/01ee546167c5b2b781efca4c49d197593c79193e
