### ISSUE TITLE
[Feature request] 希望增加对于小标题的显示

### ISSUE THREAD

**Issue by Mikachu2333** [vuepress/ecosystem#109]
### Clear and concise description of the problem

RT，问题来源于

https://github.com/DGP-Studio/Snap.Hutao.Docs/issues/119#issue-2188067764

搜索出的两个标题显示的内容相同，但实际上被重定向到了两个不同的三级标题。

### Suggested solution

显示三级标题（可选）

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress/ecosystem/assets/33315834/803a2582-17c2-4fd2-9076-2f6f97e3de77)

This should be a upstream configuration / bug.

docsearch package is outputing the dom above, so it's not our plugin's issue.
