### ISSUE TITLE
[Feature request] Add Google Tag Manager to VuePress 2

### ISSUE THREAD

**Issue by rockbenben** [vuepress/ecosystem#113]
### Clear and concise description of the problem

Is there a VuePress 2 plugin available that simplifies the deployment of Google Tag Manager, making it easier to incorporate various analytics and third-party service codes without the need to directly modify the `template.html` file?

Existing plugins appear to focus on individual analytics, making it inconvenient for potential future expansions.

### Suggested solution

- Ability to add Google Tag Manager code to all pages of the VuePress 2 website.
- Integration process should be as straightforward as possible and should not require modification of the `template.html` file.

**Comment by Mister-Hope** [comment]
I think this can be a feature which can diving down to theme.

Any reference of docs about this

**Comment by rockbenben** [comment]
> I think this can be a feature which can diving down to theme.我认为这可能是一个可以深入主题的功能。
> 
> Any reference of docs about this?有关于这方面的文档参考吗？

Refer to step 5 on the page: https://support.google.com/tagmanager/answer/14847097

**Comment by Mister-Hope** [comment]
The problem is that:

1. a plugin does not have access to `templateBuild`
2. A plugin can not make a script tag appears first

what are the tag manager for? Or what are you trying to do with it? If it's possible that loading it in head, but probably after some other tags, then a simple plugin can be made to eject the `<script>` tag to head

**Comment by Mister-Hope** [comment]
Is there any problem for adding 

```ts
[
          'script',
          {},
          `\
((w,d,s,l,i)=>{\
w[l]=w[l]||[];\
w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});\
var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';\
j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;\
f.parentNode.insertBefore(j,f);\
})(window,document,'script','dataLayer','${options.id}');\
`,
        ]
```

inside `head` option of `.vuepress/config.js` file?

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/ecosystem/pull/118

**Comment by rockbenben** [comment]
@Mister-Hope 5.2b is missing, the noscript section.
![image](https://github.com/vuepress/ecosystem/assets/28252913/1fc146c5-a431-48e0-92f4-05224708fafa)

**Comment by Mister-Hope** [comment]
A plugin can never add a content like this when script is disabled, so for this part you must edit templateBuild by you own.

**Comment by Mister-Hope** [comment]
Might need to add some hints in docs
