### ISSUE TITLE
[Feature request] plugin-shiki migrate to use shikiji

### ISSUE THREAD

**Issue by meteorlxy** [vuepress/ecosystem#12]
### Clear and concise description of the problem

[Shikiji](https://github.com/antfu/shikiji) is a pure esm rewrite of shiki, with some improvement.

### Suggested solution

Migrate from shiki to shikiji. No need to update the plugin name, as shikiji might become shiki 1.0 in the future

**Comment by nruffing** [comment]
@meteorlxy @Mister-Hope  

Looking for someone to pick this up? I would be happy to help.

**Comment by Mister-Hope** [comment]
sure, just pick it up. I am really busy with my article

**Comment by nruffing** [comment]
It doesn't look like I have permissions to assign the issue to myself but I will start working on this.

**Comment by nruffing** [comment]
Actually, is `plugin-shiki` even necessary anymore? Should we just use [`markdown-it-shikiji`](https://shikiji.netlify.app/packages/markdown-it) diectly now?

**Comment by meteorlxy** [comment]
@nruffing As I remember, that plugin has its own highlightLine and language class implementation. I'm not sure if that's compatible with our default theme, or may introduce some breaking change to theme authros. You can investigate a little more about that.

**Comment by nruffing** [comment]
The breaking changes between shiki and shikiji are documented [here](https://shikiji.netlify.app/guide/compat#breaking-changes-from-shiki).  There is a shim build that restores most of them if necessary but there are still a couple potential breaking changes to theme developers (e.g. the `css-variables` theme is no longer supported). 

It does appear that other than the `css-variables` theme all the same languages and themes are supported but the options contract passed to `codeToHtml` is changed to allow for dark and light themes to be configured.  It also looks like the rendered markup is likely to be different as well. 

We might be able to have the plugin use `markdown-it-shikiji` and shim the options to maybe support both the current `themes` type and the existing one but ultimately its a breaking change that seems like should be migrated to at some point. I will look further into the options types.
