### ISSUE TITLE
[Feature request] Support `:line-numbers=2` in prismjs

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/ecosystem#184]
### Clear and concise description of the problem

Align the behaviors between 2 highlighters

### Suggested solution

Build it!

**Comment by Mister-Hope** [comment]
I think the lineNumbersPlugin might be able to extract to `@vuepress/highlighter-helper`.

**Comment by pengzhanbo** [comment]
`prismjs` has already implemented this feature in the same way.
