### ISSUE TITLE
[Feature request] Add e2e testing

### ISSUE THREAD

**Issue by meteorlxy** [vuepress/ecosystem#19]
### Clear and concise description of the problem

Add e2e testings for ecosystem repo

### Suggested solution

Use cypress for e2e testing like the core repo.

**Comment by Mister-Hope** [comment]
Added with https://github.com/vuepress/ecosystem/commit/17b1619ba9be3385c3da27c1f1b3a6b0af951c52

A lot of e2e test may still need to be added, I will try to complete them later.
