### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by smz8023** [vuepress/ecosystem#200]
### Description

https://github.com/vuepress/ecosystem/blob/v2.0.0-rc.35/themes/theme-default/src/client/components/VPSidebarItems.vue
当前vue文件中的选择器错误：
      // get the active sidebar item DOM, whose href equals to the current route
      const activeSidebarItem = document.querySelector(
        `.vp=sidebar a.vp-sidebar-item[href="${route.path}${hash}"]`,
      )
     .vp=sidebar应该为.vp-sidebar
![image](https://github.com/vuepress/ecosystem/assets/31838004/72e39e02-55c2-4332-8454-de70dc4a0b49)

### Reproduction

https://stackblitz.com/edit/vuepress-fzwxtj?file=package.json

### Used Package Manager

npm

### System Info

```shell
版本：v2.0.0-rc.35
```

**Comment by Mister-Hope** [comment]
Already fixed in https://github.com/vuepress/ecosystem/commit/0a29075388cb435e5f95d25dc1b54abbcd343d9a

Thanks for reporting anyway.
