### ISSUE TITLE
[Feature request] Consolidate duplicate contributor names 

### ISSUE THREAD

**Issue by Jojoshua** [vuepress/ecosystem#236]
### Clear and concise description of the problem

It's not uncommon for enterprises to switch their internal email addresses so you will have git commits for the same name but different email addresses. 

### Suggested solution

The contributor names should be distinct regardless of the email address or number of commits. In the rare case it truly is actually 2 different people with the same name, having the same name twice doesn't provide any value.

**Comment by Mister-Hope** [comment]
This is a plugin git thing, we can consider merging contributors and assigning their email with the last one they use.

We need a new option for this, and I think we can either make this opt-in or make your description as default and make the current opt-in.

It should be not hard to open a pr for this, I am at covid with fever, so I would invite you to open a pr.

Looking for the option ideas feed back with @pengzhanbo and @meteorlxy .

**Comment by pengzhanbo** [comment]
I think we can merge `email`s similarly to `commits`, based on whether they have the same name, separating them with a `,`. Perhaps we should rename the field to `emails`. Should the option be named `mergeSameContributor`?
@Mister-Hope @meteorlxy

**Comment by meteorlxy** [comment]
> having the same name twice doesn't provide any value.

@Jojoshua  In fact we also display the email when hovering on the name, so it actually has some value to display duplicate names:

<img width="430" alt="image" src="https://github.com/user-attachments/assets/48bac11d-a683-410c-820a-c6900c1c1b38">

---

IMO it could be better to provide an option to let user customize the merging strategy, maybe something like:

```ts
gitPlugin({
  contributors: true,
  contributorsMerging: (a, b) => {
    // return false to avoid merging
    if (a.name !== b.name) return false
    return {
      name: a.name,
      email: a.email.endsWith('@personal.com') ? a.email : b.email,
      commits: a.commits + b.commits,
    }
  },
})
```

Or simply provide the raw contributors array directly:

```ts
gitPlugin({
  contributors: true,
  contributorsHandling: (contributors) => {
    return contributors.filter(() => { /* whatever */ })
  },
})
```

**Comment by Mister-Hope** [comment]
What about `transformContribors`?

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/ecosystem/commit/d431dc460df18b386dbff9edff27374618edf150

**Comment by Jojoshua** [comment]
Thanks for the new function!
