### ISSUE TITLE
[Bug report] Locale redirect modal should remember the user's chocie

### ISSUE THREAD

**Issue by labuladong** [vuepress/ecosystem#253]
### Description

If I choose to cancel, it would ask again when I open the page in a new tab:

<img width="793" alt="image" src="https://github.com/user-attachments/assets/104219b5-452c-4281-99d1-cb7534544b35">

I suggest remembering the user's choice, don't ask it every time. 

Maybe we can change this to `useLocalStorage`:
https://github.com/vuepress/ecosystem/blob/e2d3c23a48e2247a91529c5f9071cf84f302a6ac/plugins/tools/plugin-redirect/src/client/components/RedirectModal.ts#L33-L37

### Reproduction

https://theme-hope.vuejs.press/config/plugins/intro.html

### Used Package Manager

npm

### System Info

```shell
$ npx vuepress info

  System:
    OS: macOS 14.7
    CPU: (8) arm64 Apple M1 Pro
    Memory: 85.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
    bun: Not Found
  Utilities:
    Git: 2.39.2 - /opt/homebrew/bin/git
  Browsers:
    Chrome: 127.0.6533.73
    Edge: 129.0.2792.52
    Safari: 18.0
  npmPackages:
    @vuepress/bundler-vite: 2.0.0-rc.14 => 2.0.0-rc.14
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-rc.14
    @vuepress/client: ^2.0.0-rc.14 => 2.0.0-rc.14
    @vuepress/core:  2.0.0-rc.14
    @vuepress/markdown:  2.0.0-rc.14
    @vuepress/shared:  2.0.0-rc.14
    @vuepress/utils:  2.0.0-rc.14
    vue: ^3.4.30 => 3.4.30
    vue-router: ^4.4.0 => 4.4.0
    vuepress: 2.0.0-rc.14 => 2.0.0-rc.14
```

**Comment by Mister-Hope** [comment]
Suggest adding a `remember my choice` check box. PR welcome.
