### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by 870138612** [vuepress/ecosystem#266]
### Clear and concise description of the problem

使用mathfull作为latex的解析器会导致页面中的latex公式部分出现下拉栏，而使用katex就不会出现这种问题，但是在使用katex时，公式框内部的中文字体明显大于正文字体.

### Suggested solution

我将katex中的字体设置为 0.9em之后，公式中的中文和正文的中文字体大小差不多相等

**Comment by Mister-Hope** [comment]
- https://github.com/vuepress/ecosystem/commit/4add5f14a18a83d352419cd2d3863beb5434fb97
- https://github.com/vuepress/ecosystem/commit/c73b86f684605fede21b0879c4826baaf2d37bbb
