### ISSUE TITLE
[Bug report] Vuepress cannot use Responsive sidebar & navbar in Vue 3.4 or higher

### ISSUE THREAD

**Issue by LdoDoeg222** [vuepress/ecosystem#27]
### Description

When I use vue 3.4.0 and then run `pnpm docs:dev`, and then open my local vuepress site, the navbar and sidebar will lose their responsive capability.
当我用 vue 3.4.0 并且运行 `pnpm docs:dev`，再打开本地的 Vuepress 网页时，顶部导航和侧边栏都会失去它们的响应性。
![vuepress-in-vue3 4 0](https://github.com/vuepress/core/assets/42036737/634d07c8-f552-4a42-80a5-6035094137a4)

The guide in [guide of vuepress](https://v2.vuepress.vuejs.org/guide/getting-started.html#manual-installation) tells me to install vue normally like `pnpm add -D vue`
在[官方文档](https://v2.vuepress.vuejs.org/zh/guide/getting-started.html#manual-installation)中提到的方法，只是简单地让我直接安装 vue——`pnpm add -D vue`

This situation is the same in higher version (3.4.14, which is the lastest version)
同样的情况（指失去响应性）当然也发生在了更高版本。

However, if i install vue 3.3.13 like [the official documents](https://github.com/vuepress/docs/blob/main/package.json#L50) do, it will run responsively.
然而，如果我像[官方文档里写的一样](https://github.com/vuepress/docs/blob/main/package.json#L50)，为我的 vuepress 安装 vue 3.3.13，又可以成功运行了。
![vuepress-in-vue3 3 13](https://github.com/vuepress/core/assets/42036737/1ac6d154-9fe4-4c54-a729-f94c5de14b3e)

This problem may caused by the update of vue 3.4, which added some breaking features.
这可能是因为 vue3.4 的更新带来了一些新特性。

### Reproduction

https://github.com/LdoDoeg222/vuepress-bugrepo

### Used Package Manager

pnpm

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz      
    Memory: 5.79 GB / 15.80 GB
  Binaries:
    Node: 18.14.2 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.5.0 - D:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.39.0.
  Browsers:
    Chrome: 94.0.4606.71
    Edge: Chromium (120.0.2210.133)
  npmPackages:
    @vuepress/bundler-vite: 2.0.0-rc.0 => 2.0.0-rc.0
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli: Not Found
    @vuepress/client: 2.0.0-rc.0 => 2.0.0-rc.0
    @vuepress/core: 2.0.0-rc.0 => 2.0.0-rc.0
    @vuepress/markdown: Not Found
    @vuepress/plugin-active-header-links: Not Found
    @vuepress/plugin-back-to-top: Not Found
    @vuepress/plugin-container: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon: Not Found
    @vuepress/plugin-git: Not Found
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom: Not Found
    @vuepress/plugin-nprogress: Not Found
    @vuepress/plugin-palette: Not Found
    @vuepress/plugin-prismjs: Not Found
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data: Not Found
    @vuepress/plugin-toc: Not Found
    @vuepress/shared: Not Found
    @vuepress/theme-default: 2.0.0-rc.0 => 2.0.0-rc.0
    @vuepress/utils: Not Found
    vue: 3.4.0 => 3.4.0
    vue-loader: Not Found
    vue-router: Not Found
    vuepress: 2.0.0-rc.0 => 2.0.0-rc.0
    vuepress-vite: Not Found
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
@meteorlxy  I managed to figure out how this happens, in Vue3.4 the reactivity system is rewrite.

We previously called composition Api hooks like `useRouter` and `userRoute` in computed functions, and this works in Vue3.3 and below, while in Vue3.4, `useRouter` somehow will return `undefined` in some cases.

This issue could be solved by moving out the router and route declarations outside the `computed`:

```ts
// before
const sidebar = computed(() => 
  resolveSidebar() // called useRouter and useRoute inside it
)

// after
const router = useRouter()
const route = useRoute()

const sidebar = computed(() => 
  resolveSidebar(router, route)
)
```

I am not sure if this should be the correct fix, but the direction is correct. Vue3.4 does have different activity with composition api calls inside computed getter functions.

May need you take a deeper look at this.

**Comment by Mister-Hope** [comment]
Update: I confirmed calling composition api is not supported in Vue3.4.

I mock a composition api for `userRouter` like the following:

```ts
export const useMock = inject('mock') // mock is provided earlier
```

And the test code:

```ts
const test = computed(() => {
  const mock = useMock();

  return mock;
})

Vue 3.3 and below is working fine with no warnings.

Vue 3.4 gives an warning at dev mode:

<img width="420" alt="image" src="https://github.com/vuepress/ecosystem/assets/33315834/af3d109e-d245-4a6f-8730-df1f5b15613f">


So we probably need the change I mentioned above. However, a lot of changes may not be needed once the router pr is merged, so I'd request you to review that and publish upstream.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/ecosystem/commit/6d78f5d0972c023027f44ae891833657f1da0adb
