### ISSUE TITLE
[Bug report] Pre-transform error: Preprocessor dependency "sass-embedded" not found. Did you install it? Try `npm install -D sass-embedded`.

### ISSUE THREAD

**Issue by rex-ll** [vuepress/ecosystem#272]
### Description

Pre-transform error: Preprocessor dependency "sass-embedded" not found. Did you install it? Try `npm install -D sass-embedded`.

### Reproduction

Start the service

### Used Package Manager

pnpm

### System Info

```shell
latest
```

**Comment by Mister-Hope** [comment]
I believe the package is included in the starter template,

So a reproduction is needed

**Comment by Mister-Hope** [comment]
Oh wait, it seems that I did forget adding it in the template
