### ISSUE TITLE
[Feature request] seo插件添加Canonical 属性

### ISSUE THREAD

**Issue by sunshang-hl** [vuepress/ecosystem#289]
### Clear and concise description of the problem

从优化的角度来理解，canonical标签主要用于规范化网址，比如当网站一个页面有多个URL可以访问时，为避免权重分散，我们通过canonical标签告诉搜索引擎哪个页面地址才是主要的，同时这个URL也是我们想被收录的地址。
这里我举一个例子：

　　[http://feiyuseo.cn/123.html](https://link.zhihu.com/?target=http%3A//feiyuseo.cn/123.html)

　　[http://feiyuseo.cn/?id=123](https://link.zhihu.com/?target=http%3A//feiyuseo.cn/%3Fid%3D123)

　　以上两个地址其实打开是同一个页面，对我们用户来讲没有差别，但对搜索引擎来讲，这是不同的两个网址，从[搜索优化](https://zhida.zhihu.com/search?content_id=147667237&content_type=Article&match_order=1&q=%E6%90%9C%E7%B4%A2%E4%BC%98%E5%8C%96&zhida_source=entity)角度来说，会让百度不知道哪个网址是重要的，进而将页面权重平分掉，这样就造成收录混乱且不利于关键词的排名。

### Suggested solution

增加网页meta里的canonical标签，取值为网站域名

**Comment by Mister-Hope** [comment]
https://ecosystem.vuejs.press/zh/plugins/seo/seo/guide.html#规范链接
