### ISSUE TITLE
[Feature request] @vuepress/plugin-markdown-hint support 'details' container to unfold by default

### ISSUE THREAD

**Issue by pecliu** [vuepress/ecosystem#291]
### Clear and concise description of the problem

now,details' container in @vuepress/plugin-markdown-hint is folded by default

need config entrance to let it be fold by default

![image](https://github.com/user-attachments/assets/27b58c1a-6bc4-4b2b-aa23-0897753d1b78)

### Suggested solution

need config entrance to let it be fold by default

**Comment by Mister-Hope** [comment]
1. If you are not a native English speaker, then providing a copy with mother language would be helpful in some cases.

2. To let the container being expanded by default, adding the following snippets would be helpful:

```ts
// vuepress/client.ts
import { defineClientConfig, useRoute } from 'vuepress/client'

export default defineClientConfig({
  setup() {
    const route = useRoute()

    onMounted() {
      // Toggle all <details> open when path changes
      watch(() => route.path, () => {
        document.querySelectorAll('details').forEach((detail) => {
          detail.open = true
        })
      }, { immediate: true })
    })
  },
})
```

**Comment by Mister-Hope** [comment]
@pengzhanbo I don't think it's worthy to be further worked on, RFC here.

IMO, the goals of details is to hide some further explanations out of the main document to make the structure and content clean, while providing an easier way to access these further explanations rather than as attachement.

**Comment by pengzhanbo** [comment]
@Mister-Hope I agree with this viewpoint. If the `details` container needs to be expanded by default, it indicates that what is required in this scenario is not the `details` container, but rather containers like `tip/warning/caution/important`.
