### ISSUE TITLE
[Bug report] `plugin-photo-swipe` repeated clicks during initialization lead to duplicate instances

### ISSUE THREAD

**Issue by pengzhanbo** [vuepress/ecosystem#310]
### Description

The plugin starts initializing when the image is clicked, but due to the need to wait for dependencies to load, repeated clicks during the loading period can result in multiple instances of `photo-swipe` being created.

### Reproduction

https://theme-plume.vuejs.press/guide/components/card-masonry/

### Used Package Manager

pnpm

### System Info

```shell
-
```

**Comment by Mister-Hope** [comment]
I think moving the destroy before assigning new ids may help the problem.

https://github.com/vuepress/ecosystem/blob/4fdde2cca2c89344d692ebad7a806a48959a3d46/plugins/features/plugin-photo-swipe/src/client/composables/usePhotoSwipe.ts#L65-L86

Any better ideas? We can record a global load task for sure but I am not sure if it's needed.

**Comment by pengzhanbo** [comment]
Moving `photoSwipe?.destroy()` before `new PhotoSwipe` can somewhat resolve the issue, but there is still a problem with repeated destruction and initialization when clicking multiple times during loading. Therefore, a more reliable approach is to implement a lock to prevent multiple initializations caused by repeated clicks during loading.

Perhaps the dependencies can be preloaded during the browser's idle time after the page has finished rendering, which can also avoid loading delays on the first click.

**Comment by Mister-Hope** [comment]
The problem is that it's hard to give a time that everything is loaded yet.

After the root component mounted, there might still be task like loading page images, initializing markdown components (like ECharts, Mermaid and other things)

Any point about this?

**Comment by pengzhanbo** [comment]
Reference：
- [requestIdleCallback](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/requestIdleCallback) 
- [vueuse - useIdle](https://vueuse.org/core/useIdle/)

`requestIdleCallback` is an API supported by browsers, but there are compatibility issues with certain browser versions. 

`useIdle` is a composable API provided by VueUse, but its behavior is to check whether the user is in an active state.

For browsers that do not support requestIdleCallback, tasks can typically be added to the macro task queue, for example by using `setTimeout` instead.
