### ISSUE TITLE
[Bug report] default theme language active status is lost

### ISSUE THREAD

**Issue by meteorlxy** [vuepress/ecosystem#71]
### Description

<img width="537" alt="image" src="https://github.com/vuepress/ecosystem/assets/18205362/18f6e831-15f1-472b-a683-3f902862d51e">

### Reproduction

https://ecosystem.vuejs.press/

### Used Package Manager

pnpm

### System Info

```shell
N/A
```

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/ecosystem/commit/506e28c7a5c1cbbf5def5079a34e3575e2449891
