### ISSUE TITLE
replace workbox

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/ecosystem#72]
### Clear and concise description of the problem

See https://github.com/GoogleChrome/workbox/issues/3149

We might have other alternative ones now.

### Suggested solution

replace workbox

**Comment by DuCanhGH** [comment]
Noticed this issue referencing the Workbox issue I commented in.

I'm assuming that you are referring to Serwist as "alternative ones".

Just trying to warn you of one thing: GenerateSW has been removed. This was mentioned in the comment.

Surfing through the source code tells me that GenerateSW is being used. You may consider looking into Workbox's GenerateSW's source code and reimplementing that feature with Serwist. One thing I'd like to mention is that this requires you to... stringify `RuntimeCaching[]` by your own two hands.

Another alternative is to publish a separate package :)
