### ISSUE TITLE
[Bug report] copy code 无法在微信H5中使用

### ISSUE THREAD

**Issue by EastWoodYang** [vuepress/ecosystem#75]
copy code 无法在微信H5中使用，点击无响应

但通过 extendsMarkdown的方式 注入 markdown-it-copy 可以成功复制，但UI 需要自定义调整，有点麻烦

**Comment by EastWoodYang** [comment]
比如 把链接 https://v2.vuepress.vuejs.org/guide/getting-started.html#try-it-online 发到微信上，在微信 H5 中打开，代码部分就复制不了

比如 
![image](https://github.com/vuepress/ecosystem/assets/9335046/d84b3715-8e38-4452-921e-53c37b431fd2)
点击不会出现复制，

Google 浏览器里就没问题
<img width="608" alt="image" src="https://github.com/vuepress/ecosystem/assets/9335046/43d14345-5bd8-47d1-8c5f-aa71d0b0b637">


然后我把 https://github.com/vuepress/ecosystem/blob/0b8fff7e4a29e1a383fe44a936e45f7670031d95/plugins/plugin-copy-code/src/client/composables/useCopyCode.ts#L78 处的 `copy` 换成如下就可以在微信 H5 中正常复制了

```
const copy = (t = '') => new Promise((c, o) => {
        const n = document.createElement('textarea');
        n.value = `${t}`, document.body.appendChild(n), n.select();
        try {
            const t = document.execCommand('copy');
            document.body.removeChild(n), t ? c() : o()
        } catch (t) {
            document.body.removeChild(n), o()
        }
    })
```

**Comment by Mister-Hope** [comment]
Please read the docs carefully, copy button is disabled on mobile devices by default.

**Comment by EastWoodYang** [comment]
在自己的项目中已经打开[showInMobile](https://ecosystem.vuejs.press/plugins/copy-code.html#showinmobile) ，在微信H5中还是无法复制，强制显示复制按钮点击是无响应的，最后通过修改 `copy` 才能复制。

**Comment by EastWoodYang** [comment]
上面两张截图想表达的意思是，点击黑色代码区域时，微信H5中只会显示黄框不显示复制按钮，，Google chrome中能正常展示复制按钮。通过修改样式使复制按钮一直显示，微信H5中点击还是不发复制，点击无响应（应该是微信H5一些兼容性问题），最后修改`copy`（这个copy 是拷贝至https://github.com/ReAlign/markdown-it-copy/blob/master/lib/code.js）就能正常复制了

**Comment by EastWoodYang** [comment]
> https://v2.vuepress.vuejs.org/guide/getting-started.html#try-it-online

另外，https://v2.vuepress.vuejs.org/guide/getting-started.html#try-it-online 应该是开启了[showInMobile](https://ecosystem.vuejs.press/plugins/copy-code.html#showinmobile)

**Comment by EastWoodYang** [comment]
> Please read the docs carefully, copy button is disabled on mobile devices by default.

另外，https://v2.vuepress.vuejs.org/guide/getting-started.html#try-it-online 应该是开启了[showInMobile](https://ecosystem.vuejs.press/plugins/copy-code.html#showinmobile)

**Comment by Mister-Hope** [comment]
感谢详细的信息，我会在很晚之后去排查一下。不是特别清楚我要怎么对微信内置的浏览器进行调试。微信开发者工具还是什么？

代码复制本身也没有用什么太新的功能。有没有可能是微信禁掉了 `document.excuceCommand('copy')`？

**Comment by Mister-Hope** [comment]
更新，重新回顾了一下我用的是 vueuse 的 useClipBoard，你可以搞一个小 demo 看看这个函数能不能在微信浏览器工作，如如果不能到 vueuse仓库去找找相关issue看看有没有解决办法，或者开一个 issue？

**Comment by Mister-Hope** [comment]
![Screenshot_2024-02-22-13-58-03-41_e39d2c7de19156b0683cd93e8735f348.jpg](https://github.com/vuepress/ecosystem/assets/33315834/37b05787-bbfc-4891-b083-e4bedd437c45)

似乎微信不允许访问剪切板 api

**Comment by Mister-Hope** [comment]
我确认国内很多 App 的内置浏览器都从安全性考虑默认禁用了很多权限。

详见 https://github.com/vueuse/vueuse/issues/3008。

需要等待 antfu 的回复已确认是否可以添加一个选项叫 `fallback`，不然的话也许我们需要把源码拷贝过来自己实现一下。

**Comment by Mister-Hope** [comment]
This is considered as upstream bug, I open a pr https://github.com/vueuse/vueuse/pull/3812 that could possibly fix this, and also a feature request https://github.com/vueuse/vueuse/issues/3813
