### ISSUE TITLE
[Bug report] Sidebar heading links path missing

### ISSUE THREAD

**Issue by kvanzuijlen** [vuepress/ecosystem#81]
### Description

The URL path is missing for links to headings in the sidebar. This is also occurring on the docs of the default theme. This issue can be seen when hovering over any of the links to headings on the provided reproduction page.

### Reproduction

https://ecosystem.vuejs.press/themes/default/config.html

### Used Package Manager

npm

### System Info

```shell
-
```

**Comment by Mister-Hope** [comment]
so what's them problem?
