### ISSUE TITLE
right anchor in theme-default

### ISSUE THREAD

**Issue by zhourunjie1988** [vuepress/ecosystem#86]
### Clear and concise description of the problem

默认主题当前还不支持右侧的锚点功能，如果单个md文档内容过多，容易导致sidebar太长，现有的插件往往和最新vuepress版本之间存在兼容性问题

### Suggested solution

添加配置开关，用户可进行选择是否使用右侧锚点

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/ecosystem/issues/8
