### ISSUE TITLE
[Feature request] plugin-seo supports `Disallow: /`

### ISSUE THREAD

**Issue by Zihan-Hu** [vuepress/ecosystem#89]
### Clear and concise description of the problem

Some websites that are not open to the public and do not want to be indexed by search engines.

### Suggested solution

```ts
interface SeoPluginOptions {
  /**
   * Whether to block search engine indexing
   *
   * 是否阻止搜索引擎收录
   */
  block?: boolean
}
```

-> `robots.txt`:
```
User-agent: *
Disallow: /
```

**Comment by Mister-Hope** [comment]
Then why don't you just disable the seo plugin

**Comment by meteorlxy** [comment]
Your point might be disallowing crawlers explicitly. Then you don't need seo plugin. You can create a `.vuepress/public/robots.txt` file with the content. See [Assets > Public Files](https://v2.vuepress.vuejs.org/guide/assets.html#public-files)

**Comment by Zihan-Hu** [comment]
Got it. Thanks
