### ISSUE TITLE
[Bug report] plugin-baidu-analytics `Uncaught (in promise) Error: useClientData() is called without provider.` on production

### ISSUE THREAD

**Issue by Zihan-Hu** [vuepress/ecosystem#94]
### Description

When on production, plugin-baidu-analytics complains `Uncaught (in promise) Error: useClientData() is called without provider.` and doesn't load script.

### Reproduction

https://stackblitz.com/edit/vuepress-demo-19211d7

To reproduce:

```bash
pnpm install && pnpm build && pnpm preview
```

### Used Package Manager

pnpm

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 1.16 GB / 7.23 GB
  Binaries:
    Node: 20.10.0 - C:\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.2.3 - C:\nodejs\npm.CMD
    pnpm: 8.15.3 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: Not Found
  Utilities:
    Git: 2.37.3.
  Browsers:
    Chrome: Not Found
    Edge: Chromium (122.0.2365.92), ChromiumDev (123.0.2420.10)
  npmPackages:
    @vuepress/bundler-vite: 2.0.0-rc.8 => 2.0.0-rc.8
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli: Not Found
    @vuepress/client: Not Found
    @vuepress/core: Not Found
    @vuepress/markdown: Not Found
    @vuepress/shared: Not Found
    @vuepress/utils: Not Found
    vue: ^3.4.21 => 3.4.21
    vue-router: Not Found
    vuepress: 2.0.0-rc.8 => 2.0.0-rc.8
```

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress/ecosystem/assets/33315834/4cb749de-65b2-4026-a7b2-0145b35837b9)

rc14?

**Comment by Zihan-Hu** [comment]
@Mister-Hope updated to plugin version `2.0.0-rc.21` and core version `2.0.0-rc.9` (see reproduction), but the problem still appeared

**Comment by Zihan-Hu** [comment]
ping? This error is caused by
https://github.com/vuepress/ecosystem/blob/520a3b6bc508f5103b80950ae48538676c6f996a/plugins/plugin-baidu-analytics/src/client/composables/useBaiduAnalytics.ts#L18
